export const serverBaseUrl = import.meta.env.VITE_SERVER_BASE_URL

const keywords = [
    "Javascript",
    "Typescript",
    "MongoDB",
    "Express.js",
    "React.js",
    "Node.js",
    "RESTful API",
    "JSON",
    "AJAX",
    "Redux",
    "Webpack",
    "Babel",
    "NPM",
    "Yarn",
    "JWT",
    "GraphQL",
    "Axios",
    "MVC",
    "Virtual DOM",
    "Mongoose",
    "Passport.js",
    "Socket.IO",
    "Server-Side Rendering",
    "Material-UI",
    "Bootstrap",
    "OAuth",
    "Docker",
    "Kubernetes",
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Flask",
    "Django",
    "BeautifulSoup",
    "Requests",
    "SQLite",
    "PyTorch",
    "TensorFlow",
    "SciPy",
    "Celery",
    "OpenCV",
    "Kivy",
    "Dash",
    "Jupyter",
    "JDK",
    "JVM",
    "Spring Framework",
    "Hibernate",
    "JavaFX",
    "JDBC",
    "JUnit",
    "Maven",
    "Gradle",
    "Pointers",
    "Arrays",
    "Structures",
    "Classes and Objects",
    "Templates",
    "STL",
    "File Handling",
    "Multithreading",
    "Recursion",
    "Linked Lists",
    "Sorting Algorithms",
    "Searching Algorithms",
    "Memory Management",
    "Dynamic Memory Allocation",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "Microsoft SQL Server",
    "NoSQL",
    "Cassandra",
    "Redis",
    "Firebase",
    "Data Modeling",
    "ACID properties",
    "Indexing",
    "Normalization",
    "Joins",
    "Views",
    "Angular",
    "Vue.js",
    "WebSockets",
    "AJAX",
    "REST API",
    "JSON Web Tokens",
    "State Management",
    "GraphQL",
    "Webpack",
    "Gulp",
    "Sass",
    "LESS",
    "Bootstrap",
    "Materialize",
    "Firebase",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Heroku",
    "Git",
    "GitHub",
    "Bitbucket",
    "Continuous Integration",
    "Continuous Deployment",
    "Unit Testing",
    "Integration Testing",
    "End-to-end Testing",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Object-Oriented Programming",
    "Functional Programming",
    "Aspect-Oriented Programming",
    "Design Patterns",
    "Concurrency",
    "Parallel Programming",
    "Lambda Functions",
    "Stream Processing",
    "Internet of Things (IoT)",
    "Blockchain",
    "Big Data",
    "Artificial Intelligence",
    "Machine Learning",
    "Natural Language Processing",
    "Data Visualization",
    "Augmented Reality",
    "Virtual Reality",
    "Game Development",
    "Mobile App Development",
    "Responsive Web Design",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Microservices",
    "Serverless Architecture",
    "Containerization",
    "Kubernetes",
    "Docker Swarm",
    "Rust Programming",
    "Swift Programming",
    "Kotlin Programming",
    "Go Programming"
  ];
  const unique = new Set(keywords)
  const TopKeywords =  [...unique];
  export {TopKeywords};